stages:
  preprocess:
    cmd: make preprocess
    deps:
    - src/preprocess.py
    - Makefile
    outs:
    - data/interim/train.csv
    - data/interim/test.csv

  prepare_train_data:
    cmd: python src/prepare_train_data.py --train_size=0.9
    deps:
    - src/prepare_train_data.py
    outs:
    - data/model_input/x_train.csv
    - data/model_input/y_train.csv
    - data/model_input/x_test.csv
    - data/model_input/y_test.csv
  
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - data/model_input/x_train.csv
    - data/model_input/y_train.csv
    outs:
    - data/models/model.pickle
 