stages:
  preprocess:
    cmd: python ./houses/preprocess.py data/raw/train.csv data/interim/train.csv &
         python ./houses/preprocess.py data/raw/test.csv data/interim/test.csv
    deps:
    - houses/preprocess.py
    outs:
    - data/interim/train.csv
    - data/interim/test.csv

  prepare_train_data:
    cmd: python houses/prepare_train_data.py --train_size=0.9
    deps:
    - houses/prepare_train_data.py
    outs:
    - data/model_input/x_train.csv
    - data/model_input/y_train.csv
    - data/model_input/x_test.csv
    - data/model_input/y_test.csv

  train:
    cmd: python houses/train.py
    deps:
    - houses/train.py
    - data/model_input/x_train.csv
    - data/model_input/y_train.csv
    outs:
    - data/models/model.pickle

  evaluate:
    cmd: python houses/evaluate.py
    deps:
    - houses/evaluate.py
    - data/model_input/x_train.csv
    - data/model_input/y_train.csv
    - data/model_input/X_test.csv
    - data/model_input/y_test.csv
    outs:
    - data/model_output/metrics.txt
    - data/model_output/permutation_feature_importance.png
